### ISSUE TITLE
Whitelist requests: amazonses.com and deutschepost.de

### ISSUE THREAD

**Issue by papiertiger960ff** [schweikert/postgrey#102]
Grüezi,

I would like to request that the following entries be added to the postgrey client whitelist.

• amazonses.com
Amazon was whitelisted before but now changed the domain name of their email infrastructure. Retry behaviour remains weird.

• deutschepost.de
Misconfigured mail server with only 2h 59min 59sec of retry timeout. This leads to problems if postgrey is configured to use a delay time of 3h or more.

**Comment by pjperry** [comment]
amazonses.com is already whitelisted in postgrey_whitelist_clients:

# 2016-09-13: amazonses.com (github #35, #37, #38)
amazonses.com

**Comment by papiertiger960ff** [comment]
> amazonses.com is already whitelisted in postgrey_whitelist_clients:
> # 2016-09-13: amazonses.com (github #35, #37, #38)
> 
> amazonses.com

Oooops. But on my debian setup (which is rather recent), it's still missing. Most recent entry in my whitelist_clients is Alibaba, dating to 2015-08-19. Looks like Debian forgot to update whitelist_clients.
