### ISSUE TITLE
Version bump requested

### ISSUE THREAD

**Issue by richardbrinkman** [schweikert/postgrey#103]
The newest release is version-1.37. That’s more than 7 years ago. My first impression was that this project is not maintained any more, but if I view the commit history I see quite some commits since the latest release. Is there a reason why no newer versions are released?

I also observe that Alpine Linux used to have postgrey in their repository, but removed it since Alpine version 3.16 (released May 2022). Can it be that the reason for removing it from the repository is because postgrey has not seen recent upgrades?

**Comment by schweikert** [comment]
The code didn't change, only the whitelist, which can be updated independently.
