### ISSUE TITLE
IPv6 subnet support missing

### ISSUE THREAD

**Issue by Gnarfoz** [schweikert/postgrey#11]
After wrongly rejecting some ham mails from www.strato.de users, whose mail servers retry properly, but from different IPv6 addresses, I noticed that IPv6 subnet support just isn't there.

Luckily, someone posted a patch implementing it (and configurable subnet size) to the postgrey mailing list... way back in 2011:

https://lists.ee.ethz.ch/wws/arc/postgrey/2011-05/msg00005.html
http://www.lists.ee.ethz.ch/wws/arc/postgrey/2011-05/attachments/03-postgrey_cidr.patch

Any chance of that being integrated?

Thanks :-)

**Comment by BenediktS** [comment]
+1
Same problem here with IPv6 clients. 
Is there a way to withelist all IPv6 clients until this is patched?

**Comment by mutax** [comment]
+1 - Strato with a server also located at Strato :/

**Comment by JanSchnacki** [comment]
+1 This currently bites me with mails coming from GMX, WEB.de, Strato and an unknown number of other sources.

Unfortunately the original patch seems to have vanished from the web. Unbelievable as that seems.

**Comment by BenediktS** [comment]
I am not a perl programmer, but until someone else is comming up with a better  solution i try it with that  modifications:

https://github.com/schweikert/postgrey/compare/master...BenediktS:master

I know it is not good programming to edit IPv6 addresses with an regexpression. 
But with a direct "ip_transform" in front of it, i think it is ok.

If someone uses this modifications, don't forget to run "cpan install Net::IP::Lite" first. (I forgot it on one of my servers.... )

**Comment by tpeland** [comment]
The original (2011) patch is still available from
https://lists.ee.ethz.ch/wws/arc/postgrey/2011-05/attachments/03-postgrey_cidr.patch

It's needed now even more than 5 years ago.

**Comment by Gnarfoz** [comment]
By "still" you mean "again" - see above. Mirrored in case the mailing list archive goes down again in the future: https://gist.github.com/Gnarfoz/76614f9d9fb1d4516df1

**Comment by BenediktS** [comment]
That patch does look fine to me. 
I opened a pull request with the patch from Havard Moen:

https://github.com/schweikert/postgrey/pull/25

**Comment by schweikert** [comment]
I have integrated the patch (thanks!) and modified it a bit to remove the dependency on Net::IP. Can you maybe test my master branch?

**Comment by BenediktS** [comment]
Your master branch is running on one of our mail servers since 2 days now. (2000mails/day)
Until now there are no problems.  We will deploy the script to more servers in the next days.

**Comment by schweikert** [comment]
Thanks!
