### ISSUE TITLE
Long retry period for mails coming from outlook.com

### ISSUE THREAD

**Issue by bigon** [schweikert/postgrey#20]
Hello,

It seems that all the mails coming from outlook.com servers (all the office 365 customers that are hosting their mail) are taking a lot of time (sometimes a day) to be retried.

I guess an explicit whitelist should be added

Edit: I even think that I lost some mails because the servers never retried...

**Comment by p-schneider** [comment]
It looks like Microsoft Hotmail/Outlook.com sometimes uses mail servers in *.hotmail.com (I was sending from my hotmail.de-Address.

`NOQUEUE: reject: RCPT from blu004-omc4s32.hotmail.com[65.55.111.171]: 450 4.2.0 <destination@domain.tld>: Recipient address rejected: Greylisted, see...`
