### ISSUE TITLE
Match hostnames case-insensitive in whitelists

### ISSUE THREAD

**Issue by maiksd** [schweikert/postgrey#21]
I have incoming mail coming from addresses using upper and lowercase, like FooBar.com. When I use a simple domain name foobar.com in whitelist_clients, it seems not to match, because the comparison is case sensitive. Am I correct on this assessment?

If so, I'd suggest changing that to case insensitive, because IMHO nothing else makes sense on domain names.

**Comment by schweikert** [comment]
No, I think that it should be case insensitive already.
