### ISSUE TITLE
Problem with *.mail.alibaba.com

### ISSUE THREAD

**Issue by dervomsee** [schweikert/postgrey#26]
Hallo,
i have a problem with greylisting of *.mail.alibaba.com.
Here is a sample logfile: https://gist.github.com/dervomsee/1b01a166f5e4fceac0e4

As you can see the alibaba mailserver tries to send me (ali@***.de) a mail five times within one our.
Every time the mail gets rejected. Is this because the sending mailserver hostname and ip is changing? The sending mail address is keeping the same (aliexpressalert@aliexpress.com). 

Maybe it would be nice to include the host mail.alibaba.com to the whitelist.

Regards!

**Comment by schweikert** [comment]
Fixed in #27

**Comment by plaes** [comment]
This should also include `notice.aliexpress.com`
