### ISSUE TITLE
Option '--delay' being ignored

### ISSUE THREAD

**Issue by sjentzsch** [schweikert/postgrey#28]
Hi Developers,

I am using postgrey 1.36 on Ubuntu 14.04 and currently facing the annoying issue of me not being able to change from the default 300 sec delay time. My '/etc/default/postgrey' has the following string:
```
POSTGREY_OPTS="--inet=10023 --delay=120 --max-age=40"
```

Also, when I start postgrey manually (having killed any other postgrey process before):
```
root@vmd6930:/usr/sbin# ./postgrey --inet=10023 --delay=120 --max-age=40 -v
2015/09/24-02:18:10 postgrey (type Net::Server::Multiplex) starting! pid(3160)
Resolved [localhost]:10023 to [::1]:10023, IPv6
Resolved [localhost]:10023 to [127.0.0.1]:10023, IPv4
Binding to TCP port 10023 on host ::1 with IPv6
Binding to TCP port 10023 on host 127.0.0.1 with IPv4
Setting gid to "65534 65534"
Setting uid to "110"
2015/09/24-02:18:45 CONNECT TCP Peer: "[127.0.0.1]:35935" Local: "[127.0.0.1]:10023"
action=greylist, reason=new, client_name=mout.gmx.net, client_address=212.227.15.15, sender=********@gmx.de, recipient=*****@*********.de
2015/09/24-02:23:47 CONNECT TCP Peer: "[127.0.0.1]:35948" Local: "[127.0.0.1]:10023"
action=pass, reason=triplet found, delay=302, client_name=mout.gmx.net, client_address=212.227.15.19, sender=*********@gmx.de, recipient=*****@*********.de
^C2015/09/24-03:36:42 Server closing!
```

... still delaying 302 seconds!

Whats wrong here?
Thanks for your help!

Best regards from Munich
Sören

**Comment by schweikert** [comment]
That's just the time that it took for the second attempt and is determined by the sending server. --delay defines the minimum delay that is required.

**Comment by sjentzsch** [comment]
Thanks @schweikert, now I got it. I totally confused the delay-time :)
