### ISSUE TITLE
Postgrey seems to ignore whitelist for IPv6 connections

### ISSUE THREAD

**Issue by mamarley** [schweikert/postgrey#36]
I have a problem where it appears the domain whitelists provided with Postgrey appear to be ignored for IPv6 connections.  I have specifically noticed this with connections from outlook.com (which is on the provided whitelist), such as the following:

```
Aug 24 11:10:18 michaelmarley postfix/smtpd[23508]: connect from mail-sn1nam02on0613.outbound.protection.outlook.com[2a01:111:f400:fe44::613]
Aug 24 11:10:21 michaelmarley postgrey[2399]: action=greylist, reason=new, client_name=mail-sn1nam02on0613.outbound.protection.outlook.com, client_address=2a01:111:f400:fe44::613, sender=<redacted>, recipient=<redacted>
Aug 24 11:10:21 michaelmarley postfix/smtpd[23508]: NOQUEUE: reject: RCPT from mail-sn1nam02on0613.outbound.protection.outlook.com[2a01:111:f400:fe44::613]: 450 4.2.0 <redacted>: Recipient address rejected: Greylisted, see http://postgrey.schweikert.ch/help/michaelmarley.com.html; from=<redacted> to=<redacted> proto=ESMTP helo=<NAM02-SN1-obe.outbound.protection.outlook.com>
Aug 24 11:10:21 michaelmarley postfix/smtpd[23508]: disconnect from mail-sn1nam02on0613.outbound.protection.outlook.com[2a01:111:f400:fe44::613] ehlo=2 starttls=1 mail=1 rcpt=0/1 quit=1 commands=5/6
```

If I receive a connection from outlook.com using IPv4, the whitelist is applied correctly and no greylisting occurs.

**Comment by schweikert** [comment]
What version of postgrey are you using? And are you sure that outlook.com is whitelisted?

**Comment by mamarley** [comment]
1.36, and yes: https://github.com/schweikert/postgrey/commit/5d04c092920b539f48d8d69e7c54174c421590bc

**Comment by schweikert** [comment]
Hmmm, I just tested this and it seems to be working... Are you maybe supplying --whitelist-clients on the command-line? Are you 100% sure that the whitelist is being loaded and contains outlook.com?

**Comment by mamarley** [comment]
I am using the Debian/Ubuntu package, which does not appear to pass that argument, so it should be using the default file, which definitely contains outlook.com.  I don't know how to check if the file is actually getting loaded though.

**Comment by haraldpaulsen** [comment]
@mamarley Ubuntu does not pass the argument, but you have to pass it for it to work.

I assume you are using files in /etc/postgrey/ ? In that case, edit /etc/default/postgrey and have it look something like this:
POSTGREY_OPTS="--inet=10023"
POSTGREY_OPTS="$POSTGREY_OPTS --whitelist-clients=/etc/postgrey/whitelist_clients"
POSTGREY_OPTS="$POSTGREY_OPTS --whitelist-recipients=/etc/postgrey/whitelist_recipients"
POSTGREY_OPTS="$POSTGREY_OPTS --whitelist-clients=/etc/postgrey/whitelist_clients.local"
POSTGREY_OPTS="$POSTGREY_OPTS --whitelist-recipients=/etc/postgrey/whitelist_recipients.local"

Add any local additions in the .local-files.
