### ISSUE TITLE
whitelist_clients additions: amazon, outlook, hotmail, linkedin.

### ISSUE THREAD

**Issue by RalphCorderoy** [schweikert/postgrey#38]
a27-82.smtp-out.us-west-2.amazonses.com is an example of a client that's not covered by smtp-out.amazonses.com.

I wonder if you should also add /\.outbound\.protection\.outlook\.com$/ even though you have a list of IP address for when that list slowly becomes out of date.

/\.hotmail\.com$/ is also missing? I realise they spam a lot, but on the other hand Microsoft is going to come back and keep attempting to hand that spam over.

/^mail.-..\.linkedin\.com$/ matches their valid attempts that I see, again quite a large pool that aren't /24 equivalent.

Is a whitelist what's really wanted for some of these? It seems more that a means of defining "these are all equivalent", as the existing "check the /24" effectively does, is what's required.

**Comment by metalefty** [comment]
+1 

whitelist for Amazon SES should be `/^.*\.amazonses\.com/`.

**Comment by schweikert** [comment]
Is hotmail.com using servers with a reverse DNS of hotmail.com?

**Comment by schweikert** [comment]
I am willing to add linkedin, if it is troublesome... Do you have concrete examples? Note that the best is to create a separate issue for each.
