### ISSUE TITLE
outbound.protection.outlook.com hosts still being greylisted

### ISSUE THREAD

**Issue by websmurf** [schweikert/postgrey#45]
Hi David,

I'm running into issues with *.outbound.protection.outlook.com stil being greylisted even though I've updated the whitelist file and outbound.protection.outlook.com is in there. 
This is in my whitelist_clients file:
```
# 2016-10-28: Microsoft Exchange Online (Office 365), by Name
outbound.protection.outlook.com
```

This is in my mail.log file:

> Jan 31 14:55:36 debian postgrey[4401]: action=greylist, reason=new, client_name=mail-eopbgr00089.outbound.protection.outlook.com, client_address=40.107.0.89, sender=<redacted>, recipient=<redacted>
> Jan 31 14:55:36 debian postfix/smtpd[40896]: NOQUEUE: reject: RCPT from mail-eopbgr00089.outbound.protection.outlook.com[40.107.0.89]: 450 4.2.0 <redacted>: Recipient address rejected: Greylisted, see http://postgrey.schweikert.ch/help/juniorenzo.nl.html; from=<redacted> to=<redacted> proto=ESMTP helo=<EUR02-AM5-obe.outbound.protection.outlook.com>

I have restarted the greylist daemon and postfix, but that doesn't seem to have any effect.
Was wondering the following: shouldn't outbound.protection.outlook.com be added as a regex match? To make sure that it matches *.outbound.protection.outlook.com in stead of the fixed name outbound.protection.outlook.com?

Something like this:
`^*\.outbound\.protection\.outlook\.com$`

**Comment by schweikert** [comment]
The whitelisting entry as is should be ok, because it should also match subdomains of outbound.protection.outlook.com. Notice that 40.107.0.0/16 is also whitelisted, so something is preventing the whitelist to work as intended. Are you using version 1.37? It contains an important fix that might explain the behavior.

**Comment by websmurf** [comment]
I'm using the debian jessie package, it's currently at this version:

```
root@debian:/var/log# postgrey --version
postgrey 1.34
```

Even the SID version of debian is stuck at version 1.36 as far as I can see: 
https://packages.debian.org/sid/postgrey

Is there a way to make this work on 1.34 as well?

**Comment by schweikert** [comment]
No, sorry. See also #32

**Comment by shaysshaysbliss** [comment]
This is my email that is being used and blocked my name is Shannon Estrada and it's my Google email Shannon. Estrada 87 at gmail.com all lower case I've been hacked buy a wanted FBI Fugitive and he is cause chaos on my phone don't know what to do from here please advise all emails they have access to all apps they have access to you. 361 437 2524 if you have more questions please don't close this issue
