### ISSUE TITLE
Updated Postgrey version 1.34 to 1.37

### ISSUE THREAD

**Issue by siorac** [schweikert/postgrey#51]
Hi,
I'm trying to update my current version of postgrey 1.34 to version 1.37
But I'm still at version 1.34,  there is the following problem :

apt-get install postgrey
Reading package lists... Done
Building dependency tree
Reading state information... Done
postgrey is already the newest version.
The following packages were automatically installed and are no longer required:
  libopts25 linux-headers-3.13.0-35 linux-headers-3.13.0-35-generic
  linux-headers-3.13.0-36 linux-headers-3.13.0-36-generic
  linux-headers-3.13.0-37 linux-headers-3.13.0-37-generic
  linux-headers-3.13.0-39 linux-headers-3.13.0-39-generic
  linux-image-3.13.0-35-generic linux-image-3.13.0-36-generic
  linux-image-3.13.0-37-generic linux-image-3.13.0-39-generic pslib1
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
You have new mail in /var/mail/root

**Comment by deoren** [comment]
Posting simply as another user: 

Welcome to the limitations of your distro. 

More often than not, a specific package version is pulled in when a release is being prepared and that package is kept at that version for the life of the release. Generally only major bugs or security issues warrant an update to the package and even then it is usually back-ported changes that do not actually bump the version number of the package to what you'll find upstream.

To get the latest version of a package you generally have to find a third-party provider, luck up and find that the upstream developer provides a custom repo that you enable (e.g., nginx, Phusion Passenger, Rsyslog, MySQL, MariaDB, etc.) or go with a distro that provides rolling updates to the latest upstream packages (e.g., Gentoo, Arch Linux, etc.). You also have the option of building/installing from source, though that is requires more manual effort on your part to install and keep up to date with security patches.

**Comment by siorac** [comment]
Thanks for your explanation,
now, I understand that I am limited by the version of my distribution. But I do not want to update it immediately.
So what can I do to get around the problem with people who send me emails with hotmail addresses, and that happen to me with 24 hours late?

**Comment by schweikert** [comment]
You probably should do a postfix whitelist before postgrey using client_access. See: ﻿http://www.postfix.org/access.5.html.
Please keep questions out of github though... The mailing-list is a better place.
