### ISSUE TITLE
Add startcom.org to whitelist clients

### ISSUE THREAD

**Issue by jweiher** [schweikert/postgrey#7]
Hi,

I'm currently trying to get an SSL Cert from startssl.com, which is a PITA when using postgrey. Their process works like this:

* After you entered your mailadress in their webform, they test if the mailadress exists, by connecting to your mailserver and cutting the connection after RCPT. This is done by the host gateway.startcom.org. Using greylisting means, that you have to do this process at least twice.
* When you continue the process, they send you a "verification code", sadly not from the previous server but from another one, with a retry time of about an hour or so.

I hope it might be possible to get their domain into whitelist_clients, which would make this process for everyone easier. 

best,
Jan

**Comment by dervomsee** [comment]
I am trying to validate my email address on Startssl.com. The Server tries to connect from mta1.startcom.org and i waited for the mail for more than an hour. But Startssl has the following rule: "The program sends you a verification code which you need to submit within 15 minutes." 
Maybe it would be useful to whitelist all startcom subdomains. 

```
Nov  4 10:40:14 [...] postgrey[837]: action=greylist, reason=new, client_name=mta1.startcom.org, client_address=192.116.242.7, sender=certmaster@startcom.org, recipient=[...]
Nov  4 10:40:14 [...] postfix/smtpd[16589]: NOQUEUE: reject: RCPT from mta1.startcom.org[192.116.242.7]: 450 4.2.0 <[...]>: Recipient address rejected: Greylisted, see http://postgrey.schweikert.ch/help/dervomsee.de.html; from=<certmaster@startcom.org> to=<[...]> proto=ESMTP helo=<mta1.startcom.org>
Nov  4 10:40:15 [...] postfix/smtpd[16589]: disconnect from mta1.startcom.org[192.116.242.7]
```
