### ISSUE TITLE
CentOS 8 (epel-8) packages

### ISSUE THREAD

**Issue by robo2bobo** [schweikert/postgrey#78]
I am not sure if postgrey is still in development, but I wanted to request packages for CentOS 8 (via epel).

Thank you.

**Comment by johankok** [comment]
Please see https://bugzilla.redhat.com/show_bug.cgi?id=1766080 for progress on that EPEL package.

**Comment by robo2bobo** [comment]
CentOS 8/EPEL 8 packages are now available. Closing this ticket.
