### ISSUE TITLE
postgrey_whitelist_clients : new add & sub do_sender_substitutions & postgreyreport

### ISSUE THREAD

**Issue by Mspatulacci** [schweikert/postgrey#83]
hi,

i have add, in postgrey_whitelist_clients , this:
/^smtpfb[0-9]+-g[0-9]+\.free\.fr$/

i tried postgreyreport, i have put do_sender_substitutions.
i saw problem with BATV, i fix this with:
    if ($user =~ /^prvs=/) {
	my @a = split(/=/, $user);
	if ($#a == 2) {
	    if ($a[1] =~ /^[0-9a-f]{10}/ && $a[2] !~ /^[0-9a-f]{10}/) {
		$user = $a[2];
	    } elsif ($a[2] =~ /^[0-9a-f]{10}/ && $a[1] !~ /^[0-9a-f]{10}/) {
		$user = $a[1];
	    } else {
		# throw a coin, pick the standard
		$user = $a[2];
	    }
	}
    }
because in few case, the function return $user = $a[1].

PostGreyReport return many false positive but i don't see, do you hace test recently ?

best regards,

**Comment by schweikert** [comment]
I updated the whitelist entry for free.fr. Can you create PR for the changes that you suggest?
