### ISSUE TITLE
Recent slew of greylist bounces from your greylist

### ISSUE THREAD

**Issue by genyded** [schweikert/postgrey#92]
We send only transactional emails from our domain epapers.org via SMTP2GO. Recently we began receiving a high number of bounces from this greylist from several of the domains we send to:

http://postgrey.schweikert.ch/help/physics.auth.gr.html
http://postgrey.schweikert.ch/help/nctu.edu.tw.html
http://postgrey.schweikert.ch/help/ee.iitd.ac.in.html
http://postgrey.schweikert.ch/help/nctu.edu.tw.html

How do we resolve this? Our emails are time sensitive transactions related to students submitting technical papers to conferences on pre determined timelines.

**Comment by schweikert** [comment]
You need to contact the owners of the mail domains that you are sending mails to. Please see here to understand how greylisting works: https://en.wikipedia.org/wiki/Greylisting_(email).

I have added smtp2go.com to the official whitelist, but not everybody uses the official whitelist.

**Comment by genyded** [comment]
Thanks!
