### ISSUE TITLE
where should the whitelist files be placed actually ?

### ISSUE THREAD

**Issue by j75** [schweikert/postgrey#94]
In the commented lines at the beginning of the **postgrey_whitelist_recipients** and **postgrey_whitelist_clients**  files it is stated that both files should be placed in the **/etc/postfix** folder ; on Debian 11 these comments are changed and they claim that the folder should be **.etc/postgrey**.
Is that an error somewhere, either in Debian or here, or Debian has a modification with respect to this project?

**Comment by fleish** [comment]
It depends how you have installed postgrey.

If you used the files in git the default file location is set to `/etc/postfix`

The Debian & Ubuntu packages I'm using appear to set  the default file location to `/etc/postgrey`

You can also call `postgrey -h` which will show you these defaults for the various configuration files.

**Comment by j75** [comment]
Thanks!
